{% set name = "betterproto" %}
{% set version = "1.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/betterproto-{{ version }}.tar.gz
  sha256: 74a3ab34646054f674d236d1229ba8182dc2eae86feb249b8590ef496ce9803d

build:
  number: 1
  noarch: python
  entry_points:
    - protoc-gen-python_betterproto=betterproto.plugin:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    # backports-datetime-fromisoformat is the only blocker for a noarch version
    # dataclasses provides a no-op noarch build for py>37
    - python >=3.7
  run:
    #- backports-datetime-fromisoformat  # [py<37]
    - dataclasses
    - grpclib
    - python
    - stringcase

test:
  imports:
    - betterproto
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/danielgtaylor/python-betterproto
  summary: A better Protobuf / gRPC generator & library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
